### ISSUE TITLE
LATEST tag on docker hub is missing

### ISSUE THREAD

**Issue by matzew** [ansibleplaybookbundle/postgresql-apb#26]
Running the latest ASB, I am getting:

```

[2017-12-16T10:42:04.819Z] [ERROR] Image 'docker.io/ansibleplaybookbundle/rhscl-postgresql-apb:latest' may not exist in registry.
--
  | [2017-12-16T10:42:04.819Z] [ERROR] {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Tag":"latest"}}]}

```

and, indeed, I only see the `canary` TAG on the hub:
https://hub.docker.com/r/ansibleplaybookbundle/rhscl-postgresql-apb/tags/

**Comment by matzew** [comment]
https://hub.docker.com/r/ansibleplaybookbundle/postgresql-apb/tags/

is now present

**Comment by djzager** [comment]
https://hub.docker.com/r/ansibleplaybookbundle/postgresql-apb/tags/ is the place you look. We are no longer pushing `rhscl-postgresql-apb`.
